### ISSUE TITLE
Why is nocompatible required?

### ISSUE THREAD

**Issue by sheerun** [k-takata/minpac#117]
Here's my vimrc that works without issues:

```
packadd minpac
call minpac#init()
call minpac#add('sheerun/vim-polyglot')
```

Why is exactly nocompatible required for minpac?

**Comment by k-takata** [comment]
Adding `set nocp` in your vimrc is not necessary as I wrote in https://github.com/k-takata/minpac#basic-sample. The option will be automatically turned off when `.vimrc` is found.
Adding the line is useful to make sure that the option becomes off even if you execute vim with the `-u` option and without the `-N` option. E.g. `vim -u .vimrc`.

Anyway, the 'compatible' option should be off, because setting the option on has many side effects and I don't want to support it.

**Comment by sheerun** [comment]
Have you considered putting `set nocompatible` in plugin/minpac.vim?

**Comment by k-takata** [comment]
Any plugin should not change the 'compatible' option.

**Comment by sheerun** [comment]
you can restore compatible flag after autocommands are loaded, just like vim in its autocommands: https://github.com/vim/vim/blob/master/runtime/autoload/dist/ft.vim#L755-L757

**Comment by k-takata** [comment]
Do you want to use minpac with 'compatible'?

**Comment by sheerun** [comment]
No, I don't want to `set nocompatible` in ~/.vimrc, and at the same time be able to use `-u ~/.vimrc`

**Comment by sheerun** [comment]
plus it would make minpac documentation shorter, no need to worry about nocompatible at all

**Comment by k-takata** [comment]
I think that users should always care about the 'compatible' option if they use the `-u` option. The user should know what they are doing.

**Comment by sheerun** [comment]
ok
