### ISSUE TITLE
helptags is not called

### ISSUE THREAD

**Issue by chrisbra** [k-takata/minpac#25]
Now I have already stumbled several times over the fact that for some reason `:helptags` isn't called. Simple example, follow your [README.md](https://github.com/k-takata/minpac#basic-sample), restart Vim. Try `:h minpac` nothing happens, however note that the functions `minpac#add()` are available.

**Comment by chrisbra** [comment]
manually calling `:helptags ALL` fixes the issue however.

**Comment by k-takata** [comment]
Oh! It can happen for minpac itself, because minpac execute `:helptags` when a plugin is successfully installed for updated. However, you might have installed minpac manually by `git clone`, and I haven't updated minpac recently. So there's no trigger to execute `:helptags` for minpac.
If it is not the case, could you show more detail?

I'm not sure what is the best way to trigger `:helptags` for minpac.

**Comment by chrisbra** [comment]
Hm, yes it happened with minpac. 

Hm, if I do `call minpac#add('vim-airline/vim-airline')` is that not supposed to download and install the package if the directory does not exists? I thought it would, but it seems, it only happens on `minpac#update()`, right?

As for minpac helptags, perhaps a FileType autocommand for helpfiles and then check once if taglist('minpac') does return anything?

**Comment by k-takata** [comment]
Fixed by #27.

**Comment by k-takata** [comment]
Sorry, I forgot to answer your question.

> Hm, if I do call minpac#add('vim-airline/vim-airline') is that not supposed to download and install the package if the directory does not exists? I thought it would, but it seems, it only happens on minpac#update(), right?

Right. `minpac#add()` only add information of the specified plugin to an internal variable (which is used by `minpac#update()` and `minpac#clean()`).
Update or installation only happens when you call `minpac#update()`.

Now `minpac#update()` also checks if tags files are available. If `doc` directory exists and `doc/tags` does not exist, `:helptags` will be executed even the plugin is not updated.
