### ISSUE TITLE
Running post-update hook for YCM does not work

### ISSUE THREAD

**Issue by theodelrieu** [k-takata/minpac#36]
Hi, I managed to install all of my plugins with minpac today, however I could not finish the YouCompleteMe installation.

With vim-plug, the following line was sufficient:

`Plug 'Valloric/YouCompleteMe', {'do' : './install.py --clang-completer'}`

It seems the YCM git submodules are not updated once the plugin is installed, I tried the following with no success (the only output is `shell returned 1`)

`call minpac#add('Valloric/YouCompleteMe', {'do':'!git submodule update --init --recursive && ./install.py --clang-completer'})`

This is not really blocking, I can perform this by hand, but that'd be great if it was supported :)

**Comment by k-takata** [comment]
Sorry for the late response.

Isn't it just taking very long time? I try installing YCM with the following setting, and it takes over an hour to clone all submodules.

```vim
call minpac#add('Valloric/YouCompleteMe', {'do': '!./install.py --clang-completer'})
```

If plugins were successfully installed or updated, you will see a message like this:

```
All plugins are up to date. (Updated: 0, Newly installed: 1)
```

You can also see this message later with the `:messages` command. If this message is not shown, the update might be still in progress. (It might be better if a user can easily know whether the update has been finished or not, however currently minpac doesn't provide a way for that.)

Unfortunately, `./install.py` failed in my environment because cmake was not installed. Currently the output of `'do'` cannot be seen by `:message`.

**Comment by theodelrieu** [comment]
Oh, I didn't wait that long obviously, but I was a bit confused since it didn't give me any information about what was going on. IIRC, I was back at my shell prompt, I was not stuck inside vim.

Before I was using `vim-plug`, and the post hook was clearly visible inside `vim`, do you have an idea of how hard it would be to implement?

I'm a complete n00b when it comes to vim coding, so I have no idea of what it takes to implement.

**Comment by k-takata** [comment]
> it didn't give me any information about what was going on.

I think minpac should show a message when a user tries to close Vim while update is still going on.

> do you have an idea of how hard it would be to implement?

No idea for now. Need time.

**Comment by k-takata** [comment]
I tired `git submodule update --init --recursive --depth=1` to reduce the time for cloning submodules, but it didn't work as expected.

**Comment by theodelrieu** [comment]
Maybe it had to do with your bandwidth, I did it manually after closing Neovim, and it was pretty quick.

I shall try again at home this week-end.

**Comment by theodelrieu** [comment]
Sorry for the late reply. I tried again to install YCM and this time it worked.
It just took a long time to start downloading libclang, but everything is working fine!
