### ISSUE TITLE
Add way to update to stable releases only

### ISSUE THREAD

**Issue by jsatk** [k-takata/minpac#71]
As far as I can tell minpac only has the ability to pull in updates from the `master` via git.  I'd love to be able to run `:PackUpdate` and have it only pull in new releases – which in my experience is a much better indicator of stability than what's in `master`.

**Comment by k-takata** [comment]
It's not easy to define what is stable version. It depends on each plugin.
If a plugin has the `stable` branch, you can use `call minpac#add('url', {'branch': 'stable'})`.
If you want to get only tagged versions, it's not easy, because git doesn't provide an easy way to do so.
Please use the `'rev'` option and set the tag name manually.

**Comment by jsatk** [comment]
Make's sense.  Thanks!

**Comment by kassio** [comment]
What about upgrading only on new tags? I think this would be a good way to define stable releases.

For reference, it seems that [vim-plug](https://github.com/junegunn/vim-plug) has support to upgrade only on new tags. 😄

**Comment by k-takata** [comment]
Thank you for the information. It seems that vim-plug uses `git tag --list --sort -version:refname` to get the latest tag. It might be also used for minpac.

**Comment by k-takata** [comment]
Support updating only tags by `{'rev': '*'}`.
